# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Monday' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

 pod 'OOMDetector'
 pod 'matrix-wechat'
 pod 'YYCategories'
 pod 'AFNetworking', '~> 4.0'

  # Pods for Monday

end

