# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVVMDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'Masonry', '~> 0.6.4'
  pod 'ReactiveCocoa', '~> 2.5'

  # Pods for MVVMDemo


  target 'MVVMDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MVVMDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
